language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run test
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
