language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - lts/*
script:
  - npm run build
after_success:
  - npm run report-coverage
  - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
  - npx semantic-release
install:
  - "npm install @blueeast/bluerain-os"
  - "npm install react"
  - "npm install react-dom"
  - "npm install"
