"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var _1 = require("../");
var bluerain_os_1 = require("@blueeast/bluerain-os");
var react_1 = require("@storybook/react");
bluerain_os_1.default.boot({ renderApp: false });
var Text = bluerain_os_1.default.Components.get('Text');
var Image = bluerain_os_1.default.Components.get('Image');
react_1.storiesOf('Button', module).add('Primary button with label in Child', function () { return <_1.default color="primary"><Text>Dark</Text></_1.default>; });
react_1.storiesOf('Button', module).add('Default button without Text tag in Child', function () { return <_1.default color="default">Default</_1.default>; });
react_1.storiesOf('Button', module).add('Accent button with style prop', function () { return <_1.default color="accent" style={{ backgroundColor: 'purple', borderColor: 'purple' }}>Customm Purple</_1.default>; });
react_1.storiesOf('Button', module).add('Inherit button with onClick prop', function () { return <_1.default color="inherit" onClick={function () { console.log('I was clicked'); }}>onClick</_1.default>; });
react_1.storiesOf('Button', module).add('Contrast button with disabled prop true', function () { return <_1.default color="contrast" disabled>Disabled</_1.default>; });
react_1.storiesOf('Button', module).add('Accent button with href prop', function () { return <_1.default color="accent" href="https://www.facebook.com">href</_1.default>; });
react_1.storiesOf('Button', module).add('Primary button with onClick prop', function () { return <_1.default color="primary" fullWidth>FullWidth</_1.default>; });
react_1.storiesOf('Button', module).add('Contrast button with active prop true', function () { return <_1.default color="contrast" active>Active</_1.default>; });
react_1.storiesOf('Button', module).add('Accent button with bordered prop true', function () { return <_1.default color="accent" bordered>Bordered</_1.default>; });
react_1.storiesOf('Button', module).add('Link button ', function () { return <_1.default color="link">Link</_1.default>; });
react_1.storiesOf('Button', module).add('Accent Rounded button ', function () { return <_1.default color="accent">Rounded</_1.default>; });
react_1.storiesOf('Button', module).add('Primary button with iconLeft prop', function () { return <_1.default color="primary" iconLeft={<img src="https://getbootstrap.com/assets/img/bootstrap-stack.png" width="15" height="15"/>}>Icon Left</_1.default>; });
react_1.storiesOf('Button', module).add('Contrast button with iconRight prop', function () { return <_1.default color="contrast" iconRight={<img src="https://getbootstrap.com/assets/img/bootstrap-stack.png" width="15" height="15"/>}>Icon Right</_1.default>; });
react_1.storiesOf('Button', module).add('Primary button with fab prop', function () { return <_1.default color="primary" fab>FAB</_1.default>; });
react_1.storiesOf('Button', module).add('Primary button with fab prop and small prop', function () { return <_1.default color="primary" fab small>sm</_1.default>; });
react_1.storiesOf('Button', module).add('Accent button with large prop true', function () { return <_1.default color="accent" large>Large</_1.default>; });
react_1.storiesOf('Button', module).add('Default button with small prop true', function () { return <_1.default color="default" small>Small</_1.default>; });
